accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    ]

osmadeittest/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url('', include('posts.urls')),
    url('accounts/', include('accounts.urls')),
    url('admin/', admin.site.urls),
    url('posts/', include('posts.urls')),
    url('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create_post, name='newpost'),
    url(r'^details/(?P<id>\d+)/$', views.details, name='details')
]

trial/trial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField

from django.db import models

from datetime import  datetime
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = RichTextUploadingField()
    image = models.ImageField(default='default.png',blank=True)
    created_at = models.DateTimeField(default=datetime.now,blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Posts'

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'image']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Views

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            #log the user in
            user = form.save()
            login(request, user) 
            return redirect('posts:index')

    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html',{'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,render
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def index(request):
    posts = Post.objects.all()[:10]
    context = {
        'title': 'Latest Posts',
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def details(request,id):
    post = Post.objects.get(id=id)

    context = {
        'post': post
    }
    return render(request, 'posts/details.html', context)

@login_required(login_url='/accounts/login')
def create_post(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid:
            # save article to db
            return redirect("posts:index")
    else:
        form = forms.CreatePost()
    return render(request, 'posts/create_post.html', {'form': form})

accounts/templates/accounts/layout.html
 {% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="{% static 'materialize-css/dist/css/materialize.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'mystyles.css' %}">
    <title>{{title}}</title>
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">OSMadeIT</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="#"><span class="badge badge-light border border-info">Home</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><span class="badge badge-light">Profile</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><span class="badge badge-light">Popular Feed</span></a>
                </li>
              </ul>
            </div>
          </nav>
        <div>
            <center>
                <header class="container center-align"><h3 class="display-4">User Accounts</h3></header>
            </center>
        </div>
        <div class="">
            {% block content %}
            {% endblock %}
        </div>
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'materialize-css/dist/js/materialize.min.js' %}"></script>
    </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/layout.html' %}

{% block content %}
<div class="container">
        <div class="form-group">
    <h5>Login</h5>
        <form class="card-text" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
        </form>
</div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}

{% block content %}

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h5>Signup</h5>
            <form class="card-text" action="{% url 'accounts:signup' %}" method="POST">
                
            {% csrf_token %}
            {{form}}
            
            <br>
            <button type="submit" class="btn tooltipped">Signup</button>
            </form>
    </div>
    <div class="col-3"></div>
</div>


{% endblock %}

posts/templates/posts/create_post.html
{% extends "posts/layout.html" %}

{% block content %}
<div class="col-md-8 offset-md-2">
    <form action="{% url 'posts:index' %}" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
{% endblock content %}

posts/templates/posts/details.html
{% extends 'posts/layout.html' %}


{% block content %}
    <blockquote>{{post.title}}</blockquote>
    <div class="card">
        <div class="card-content">
            <img class="img-fluid" src="{{post.image.url}}">
            <p class="flow-text">{{post.body|safe}}</p>
        </div>        
    </div>
    <div class="card-action">
        {{post.created_at}}
    </div>
<a href="/posts" class="btn">Go Back</a>
{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/layout.html' %}
{% load static %}

{% block content %}
    <h4 class="center-align red lighten-3">{{title}}</h4>

<!-- Display the last ten posts in LIFO format -->
    {% for post in posts %}
    
    <div class="row">
        <div class="col-sm-4 col-md">
            <h5>{{post.title}}</h5>
            <img class="img-fluid" src="{{post.image.url}}" alt="Card image cap">
            <blockquote class="blockquote">
                <p class="mb-0 text-justify">{{post.body|safe}}</p>
            </blockquote>
            <a href="/posts/details/{{post.id}}" class="btn btn-primary">Read more...</a>
            <footer class="blockquote-footer">Posted on {{post.created_at}}</footer>
        </div>
    </div>

    {% endfor %}

{% endblock %}

posts/templates/posts/layout.html
 {% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="{% static 'materilize-css/dist/css/materialize.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <title>{{title}}</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'posts:index' %}">
                  {% if user.is_authenticated %}
                  {{'Welcome'}}<br>{{user}}
                  {% else %}
                  {{'You are not logged in'}}
                  {% endif %}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <form class="form-inline my-2 my-lg-0">
                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="/posts/"><span class="badge badge-light border border-info">Home</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#"><span class="badge badge-light">Profile</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#"><span class="badge badge-light">Popular Feed</span></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:newpost' %}"><span class="badge badge-light">New Post</span></a>
                    </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="badge badge-light">Account</span>
                        </a>
                        <form class="dropdown-menu" aria-labelledby="navbarDropdown" action="{% url 'accounts:logout' %}"  method="post">
                          {% if user.is_authenticated %}
                          <button class="dropdown-item" type="submit" href="{% url 'accounts:logout' %}"><span class="badge badge-light">Logout</span></button>
                          {% else %}
                          <button class="dropdown-item" type="submit" href="{% url 'accounts:login' %}"><span class="badge badge-light">Login</span></button>
                          {% csrf_token %}
                          {% endif %}
                          <a class="dropdown-item" href="#"><span class="badge badge-light">Settings</span></a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#"><span class="badge badge-light">Help</span></a>
                        </form>
                      </li>
                  </ul>
                </div>
              </nav>
              <hr class="my-4">
                  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                      <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                      </ol>
                      <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="carousel-caption d-none d-md-block">
                            <h5>Lorem ipsum dolor sit amet.</h5>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem amet architecto dolor reiciendis blanditiis ea.</p>
                          </div>
                          <img class="d-block w-100" src="{% static 'images/IMG_0351.jpg' %}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Lorem ipsum dolor sit amet.</h5>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem amet architecto dolor reiciendis blanditiis ea.</p>
                              </div>
                          <img class="d-block w-100" src="{% static 'images/IMG_0351.jpg' %}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Lorem ipsum dolor sit amet.</h5>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem amet architecto dolor reiciendis blanditiis ea.</p>
                              </div>
                          <img class="d-block w-100" src="{% static 'images/IMG_0351.jpg' %}" alt="Third slide">
                        </div>
                      </div>
                      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
    <center>
        <header class="container center-align"><h1>OSMakingIT Blog</h1></header>
    </center>
    <div class="container">
        {% block content %}
        {% endblock %}
        <a href="/admin" style="text-decoration: none; display: block;" class="center-align"><button class="btn">Admin login</button></a>
    </div>
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'materialize-css/dist/js/materialize.min.js' %}"></script>
    <script>
      jQuery(function($){
        $('img').addClass('img-fluid');
      });
    </script>
</body>
</html>